# Generated by Django 5.0.3 on 2024-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('addpatients_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('addpatients_linel', models.CharField(max_length=50)),
                ('addpatients_line2', models.CharField(max_length=59)),
                ('landmark', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=38)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('bank_details_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('pancard_number', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('personal_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_weight', models.FloatField()),
                ('patient_height', models.PositiveIntegerField()),
                ('patient_marital_status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried'), ('divorced', 'divorced'), ('widow', 'widow')], default='unmarried', max_length=20)),
                ('patient_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('trans', 'trans')], max_length=10)),
                ('patient_is_handicap', models.BooleanField(default=False)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_aadhar_card_number', models.CharField(max_length=16)),
            ],
        ),
    ]
