# Generated by Django 5.0.3 on 2024-03-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(default='', max_length=50)),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_weight', models.FloatField()),
                ('patient_height', models.PositiveIntegerField()),
                ('patient_marital_status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried'), ('divorced', 'divorced'), ('widow', 'widow')], default='unmarried', max_length=20)),
                ('patient_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('trans', 'trans')], max_length=10)),
                ('patient_is_handicap', models.BooleanField(default=False)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_aadhar_card_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
